import tables
import options

import frontend
import ast
import bytecodebuilder
import opcodes

proc printAst(input: string = "main.pan") =
    let outputAst = input.parseFile()
    if outputAst.isSome():
        echo outputAst.get()

proc printByteCode(input: string = "main.pan") =
    let outputAst = input.parseFile()
    if outputAst.isSome():
        echo outputAst.get().byteCode()

when isMainModule:
    import cligen
    dispatchMulti([
        printAst,
        doc="print the generated ast of the input file given",
        cmdName="ast",
    ], [
        printByteCode,
        doc="print the generated byte code of the input file given",
        cmdName="bytecode",
    ])