name: Nim

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout github repo (+ download lfs dependencies)
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Setup nim
      uses: jiro4989/setup-nim-action@v1

    - name: Build
      run: |
        ln -s $GITHUB_WORKSPACE/libLLVM-11.so /usr/lib
        nimble build -Y --verbose

    - name: Tests
      run: nimble test -Y --verbose
