name: Nim

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Date
      id: get-date
      run: echo "::set-output name=date::$(date "+%Y-%m-%d")"
      shell: bash

    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-devel-latest-${{ steps.get-date.outputs.date }}

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}

    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: "devel --latest"

    - name: Run tests
      run: nimble test -y --verbose
